site_name: Kyu Hyun Lee
site_url: http://khl02007.github.io
nav:
  - About: index.md
  - Blog: blog/index.md
theme: 
  name: null
  custom_dir: 'cinder'
  # nav_style: dark
  # name: material
  # icon: 
  #   logo: material/brain
  # palette:
  #   scheme: slate
  #   primary: black
    # accent: indigo
  # font:
  #   text: Roboto
  #   code: Roboto Mono
  # features:
  #   - navigation.tabs
  #   - navigation.tabs.sticky
  #   - navigation.sections
  #   - navigation.indexes
  # custom_dir: overrides
# plugins:
#   - search
#   - blog
#   - tags
markdown_extensions:
  - attr_list
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
  - footnotes
